language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
python:
  - "3.4"
before_script:
  - dotnet restore
  - chmod +x build.sh
script:  
  - ./build.sh --quiet verify
notifications:
  email:
    recipients:
      - $RECIPIENT
    on_success: never
    on_failure: always
before_deploy:
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.1.4
  - sudo apt-get install python3
  - sudo apt-get install -y python3-pip
  - pip3 install requests
  - sudo apt-get install nodejs
  - python3 before_deploy.py $APPSETTINGS_URL $APPSETTINGS_TOKEN
  - cd FamilyArchive.Application/
  - dotnet ef database update
  - npm install
  - npm run build
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  on:
    branch: develop