language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
python:
  - "3.4"
before_script:
  - dotnet restore
  - chmod +x build.sh
script:  
  - ./build.sh --quiet verify
notifications:
  email:
    recipients:
      - $RECIPIENT
    on_success: never
    on_failure: always
before_deploy:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install nodejs
  - npm install
  - npm run build
  - python3 before_deploy.py $DB_SERVER $DB_PORT $DB_NAME $DB_USER $DB_PASSWORD
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  on:
    branch: develop